import { Router, type IRouter } from "express";
import { requireAuth } from "../middlewares/auth.js";
import { requireFeature } from "../middlewares/features.js";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import productsRouter from "./products.js";
import salesRouter from "./sales.js";
import dashboardRouter from "./dashboard.js";
import reportsRouter from "./reports.js";
import settingsRouter from "./settings.js";
import catalogRouter from "./catalog.js";
import stockRouter from "./stock.js";
import companiesRouter from "./companies.js";
import paymentRouter from "./payment.js";
import alertsRouter from "./alerts.js";
import notificationsRouter from "./notifications.js";
import customersRouter from "./customers.js";
import suppliersRouter from "./suppliers.js";
import purchasesRouter from "./purchases.js";
import stockCountsRouter from "./stock-counts.js";
import financeRouter from "./finance.js";
import branchesRouter from "./branches.js";
import integrationsRouter from "./integrations.js";
import extIntegrationsRouter from "./ext-integrations.js";
import subscriptionsRouter from "./subscriptions.js";
import storageRouter from "./storage.js";
import documentsRouter from "./documents.js";
import financeDocumentsRouter from "./finance-documents.js";
import bankingRouter from "./banking.js";
import financeDashboardRouter from "./finance-dashboard.js";
import notificationRulesRouter from "./notification-rules.js";
import personnelRouter from "./personnel.js";
import campaignsRouter from "./campaigns.js";
import catalogSettingsRouter from "./catalog-settings.js";
import ordersManageRouter from "./orders-manage.js";
import customerGroupsRouter from "./customer-groups.js";
import orderAnalyticsRouter from "./order-analytics.js";
import networkRouter from "./network.js";
import b2bRouter from "./b2b.js";
import b2bOrdersRouter from "./b2b-orders.js";
import b2bCatalogRouter from "./b2b-catalog.js";
import channelsRouter from "./channels.js";
import einvoiceRouter from "./einvoice.js";
import marketplaceRouter from "./marketplace.js";
import profitRouter from "./profit.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/products", productsRouter);
router.use("/sales", salesRouter);
router.use("/stock", stockRouter);
router.use("/dashboard", dashboardRouter);
router.use("/reports", reportsRouter);
router.use("/settings", settingsRouter);
router.use("/catalog", catalogRouter);
router.use("/companies", companiesRouter);
router.use("/payment", paymentRouter);
router.use("/alerts", alertsRouter);
router.use("/notifications", notificationsRouter);
router.use("/customers", customersRouter);
router.use("/suppliers", suppliersRouter);
router.use("/purchases", purchasesRouter);
router.use("/stock-counts", stockCountsRouter);
router.use("/finance", financeRouter);
router.use("/branches", branchesRouter);
router.use("/integrations", integrationsRouter);
router.use("/ext-integrations", extIntegrationsRouter);
router.use("/subscriptions", subscriptionsRouter);
router.use(storageRouter);
router.use(documentsRouter);
router.use("/finance-documents", financeDocumentsRouter);
router.use("/banking", requireAuth, requireFeature("finance.banking"), bankingRouter);
router.use("/finance-dashboard", requireAuth, requireFeature("profit.dashboard"), financeDashboardRouter);
router.use(notificationRulesRouter);
router.use(requireAuth, requireFeature("hr.staff"), personnelRouter);
router.use(campaignsRouter);
router.use(catalogSettingsRouter);
router.use(orderAnalyticsRouter);
router.use(ordersManageRouter);
router.use(customerGroupsRouter);
router.use("/network", networkRouter);
router.use("/b2b", b2bRouter);
router.use("/b2b/orders", b2bOrdersRouter);
router.use("/b2b/catalog", b2bCatalogRouter);
router.use("/channels", channelsRouter);
router.use("/einvoice", requireAuth, requireFeature("einvoice.basic"), einvoiceRouter);
router.use("/marketplace", requireAuth, requireFeature("marketplace.basic"), marketplaceRouter);
router.use("/profit", requireAuth, requireFeature("profit.dashboard"), profitRouter);
import accountantRouter from "./accountant.js";
import reportsOfficialRouter from "./reports-official.js";
import budgetsRouter from "./budgets.js";
import importsRouter from "./imports.js";
import productionRouter from "./production.js";
import loyaltyRouter from "./loyalty.js";
import currencyRouter from "./currency.js";
router.use("/accountant", requireAuth, requireFeature("accountant.panel"), accountantRouter);
router.use("/reports-official", requireAuth, requireFeature("accountant.panel"), reportsOfficialRouter);
router.use("/budgets", requireAuth, requireFeature("profit.dashboard"), budgetsRouter);
router.use("/import", importsRouter);
router.use("/production", requireAuth, requireFeature("production.bom"), productionRouter);
router.use("/loyalty", requireAuth, requireFeature("loyalty.points"), loyaltyRouter);
router.use("/currency", requireAuth, requireFeature("currency.multi"), currencyRouter);

// Sprint 72 — Gerçek Kârlılık Motoru (paket kapıları router içinde)
import profitEngineRouter from "./profit-engine.js";
router.use("/profit-engine", profitEngineRouter);

export default router;
