// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ticarium365/LoginScreen.tsx": () => import("../components/mockups/ticarium365/LoginScreen.tsx"),
  "./components/mockups/ticarium365/LogoConcepts.tsx": () => import("../components/mockups/ticarium365/LogoConcepts.tsx"),
  "./components/mockups/ticarium365/Pricing.tsx": () => import("../components/mockups/ticarium365/Pricing.tsx"),
  "./components/mockups/ticarium365/Sidebar.tsx": () => import("../components/mockups/ticarium365/Sidebar.tsx")
};
