kind = "web"
previewPath = "/"
title = "Ticarium365"
version = "1.0.0"
id = "artifacts/prosan"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19971

[services.development]
run = "pnpm --filter @workspace/prosan run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/prosan", "run", "build" ]
publicDir = "artifacts/prosan/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19971"
BASE_PATH = "/"
